first_project/first_app/urls.py
from django.urls import path
from first_app import views

# template tagging
app_name = 'first_app'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('logout/', views.user_logout, name = 'logout'), 
    path('special/', views.special, name = 'special'),
    path('user_login/', views.user_login, name = 'user_login'),
    path('register/', views.register, name = 'register'),
    path('relative/', views.relative, name = 'relative'),
    path('other/', views.other, name = 'other'),
    path('formpage/', views.form_name_view, name = 'formpage'),
    path('userdetails/', views.user_details, name = 'user_details'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    # path('', views.index, name = 'index'),
    path('', include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model) : 

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additionsal classes 
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username






class Topic(models.Model) : 
    top_name = models.CharField(max_length = 264, unique = True)

    def __str__(self) : 
        return self.top_name

class Webpage(models.Model) : 
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length = 264, unique = True)
    url = models.URLField(unique = True)

    def __str__(self) : 
        return self.name

class AccessRecord(models.Model) : 
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self) : 
        return str(self.date)
    

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

# def check_for_name(value):
#     if value[0] == value[0].lower() :
#         raise forms.ValidationError("Name Should Start With The Capital Letter!")

class UserForm(forms.ModelForm) : 
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta() : 
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta() :
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')





class FormName(forms.Form) : 
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again ")
    text = forms.CharField(widget = forms.Textarea)
    # botcatcher = forms.CharField(required = False, widget = forms.HiddenInput, validators = [validators.MaxLengthValidator(0)])

    # def clean_botcatcher(self) : 
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0 :
    #         raise forms.ValidationError("Gotcha Bot!!!")
    #     return botcatcher

    def clean(self) :
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['verify_email']

        if email != vemail :
            raise forms.ValidationError("Email did'n Match !!!!! ")

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from first_app.models import Topic, Webpage, AccessRecord
from first_app import forms

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def index(request) :
    cont_dict = {'name':'Chetan Bhogade', 'number':100}
    return render(request, 'first_app/index.html', cont_dict)

@login_required
def special(request):
    return HttpResponse("Your are login, Nice")

@login_required
def user_logout(request) : 
    logout(request)
    return HttpResponseRedirect(reverse('first_app:index'))


def register(request):
    registered = False
    
    if request.method == 'POST':
        user_form = forms.UserForm(data = request.POST )
        profile_form = forms.UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid() : 
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pics' in request.FILES : 
                profile.profile_pic = request.FILES['profile_pics']
            
            profile.save()

            registered = True 
        else : 
            print(user_form.errors, profile_form.errors)
    else : 
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()
    
    return render(request, 'first_app/register.html', {
                                                        'user_form' : user_form, 
                                                        'profile_form' : profile_form, 
                                                        'registered' : registered
                                                        })


def user_login(request) : 

    if request.method == 'POST' : 
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user : 
            if user.is_active : 
                login(request, user)
                return HttpResponseRedirect(reverse('first_app:index'))
            else : 
                return HttpResponse('Account not Active')
        else : 
            print("Someone try to login and failed!")
            print(f"Username : {username} and password : {password}")
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'first_app/login.html', {})




def other(request) :
    return render(request, 'first_app/other.html')

def relative(request) :
    return render(request, 'first_app/relative_url_templates.html')

def user_details(request) : 
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records' : webpage_list}
    return render(request, 'first_app/user_details.html', context = date_dict)

def form_name_view(request) : 
    form = forms.FormName()

    if request.method == 'POST' : 
        form = forms.FormName(request.POST)

        if form.is_valid() : 
            print("Validation successful!")
            print("Name : " + form.cleaned_data['name'])
            print("Email : " + form.cleaned_data['email'])
            print("Text : " + form.cleaned_data['text'])
            
    return render(request, 'first_app/form_page.html', {'form' : form})

first_project/templates/first_app/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title></title>
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'first_app:index' %}">Chetan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:other' %}">Other</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:user_details' %}">User Details</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:user_login' %}">Login</a>
                    </li>
                    {% endif %}


                </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        {% block body_block %}
        <!-- Anything outside this block will be inherited if you extend! -->
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Form Page</title>
</head>

<body>
    <div class="container">
        <h1>Fill out the form : </h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class = "btn btn-primary" value="Submit">
        </form>


    </div>

</body>

</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to the 'index.html' page.</h1>
        <h2>This is the home page our website</h2>
        <div class="jumbotron">
            {{ name }}
            <!-- <h5>{{name | cut:"Bhogade"}}</h5><br> -->
            <!-- <h5>{{number | add:'55'}}</h5> -->
        </div>
    {% endblock %}

first_project/templates/first_app/login.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>Please Login</h1>
            <form action="{% url 'first_app:user_login' %}" method="post">
                {% csrf_token %}
                <label for="username">Username: </label>
                <input type="text" name="username" placeholder="Enter username">

                <label for="password">Password: </label>
                <input type="password" name="password" placeholder="Password">

                <input type="submit" value="Login">
            </form>
        </div>
    {% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to 'other.html' page</h1>
        <h2>This the example of template inheritance!</h2>
    {% endblock %}

first_project/templates/first_app/register.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load staticfiles %}
    {% block body_block %}
        <div class="jumbotron">
            {% if registered %}
                <h1>Thank You For Registering!</h1>
            {% else %}
                <h1>Register Here!</h1>
                <h3>Fill out the Form: </h3>

                <form enctype="multipart/form-data", method="POST">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" value="Register">

                </form>

            {% endif %}
        </div>

    {% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Relative Templates</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE TEMPLATES. </h1>
    <a href="{% url 'first_app:other' %}">The Other Page</a><br>
    <a href="{% url 'admin:index' %}">Goto the Admin Page</a><br>
    <a href="{% url 'first_app:index' %}">Link to Index Page</a>
    
</body>
</html>

first_project/templates/first_app/user_details.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Access Records</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>

<body>
    <div class="container">
        <div class="jumbotron">
            <h1>Hii, Welcome to django level two </h1>
            <h2>Here are your access records</h2>

            <div class="djangotwo">
                {% if access_records %}
                <table>
                    <thead>
                        <th>Site Name</th>
                        <th>Date accessed</th>
                    </thead>

                    {% for acc in access_records %}
                    <tr>
                        <td> {{ acc.name }} </td>
                        <td> {{ acc.date }} </td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <p>NO ACCESS RECORDS FOUND</p>
                {% endif %}
            </div>

            <h1 class = 'p-3'>For Forms Goto the 'formpage/' url.</h1>


        </div>
    </div>

</body>

</html>